#
# check the doc at
# https://goreleaser.com/customization/build/
#
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  -
    binary: github-go-cli
    ldflags: -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

# https://goreleaser.com/customization/archive
archives:
  -
    builds:
      - github-go-cli
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
        
# https://goreleaser.com/customization/nfpm
nfpms:
  -
    vendor: github-go-cli
    homepage:  https://github.com/lucasafonsokremer/github-go-cli
    maintainer: "Lucas Afonso Kremer"
    description: "Access all of GitHub’s public API functionality from your command-line."
    license: Apache-2.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/local/bin
